[repo]

[release]
default_branch = "master"
remote = "origin"
tag_format = "{name}-v{version}"

[bumps]
v0 = "cargo"
major = []
minor = ["feat"]
patch = ["fix", "chore", "refactor", "docs"]
skip = []
